config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  root to: "hairs#index"
  resources :hairs do
    resources :orders do
      member do
        get :checkout
        get :success
        get :cancel
      end
    end
    resources :reviews, only: [:new, :create, :edit]
  end
  get "/dashboard", to: "pages#dashboard"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hair.rb
class Hair < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :users, through: :orders
  has_many :reviews, dependent: :destroy
  belongs_to :admin, class_name: "User", optional: true
  has_one_attached :photo
  validates :photo, :name, :price, :length, :texture, :origin, :quantity, presence: true
  validates :length, inclusion: { in: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40] }
  validates :texture, inclusion: { in: ["Straight", "Body Wave", "Deep Wave", "Loose Wave", "Water Wave", "Kinky Curly", "Yaki Straight", "Kinky Straight", "Vietnamese Straight", "Cambodian Wavy", "Burmese Curly"] }
  validates :origin, inclusion: { in: ["Peruvian", "Brazilian", "Indian"] }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :hair
  belongs_to :user
  validates :price, presence: true
  validates :status, inclusion: { in: ["pending", "paid", "failed"], message: "%{value} is not a valid status" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hair
  belongs_to :user
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :order
  has_many :hairs, through: :order

  def admin?
    self.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # include Pundit::Authorization

  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :dateofbirth, :phone_number, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :dateofbirth, :phone_number, :address])
  end

  # private

  # def skip_pundit?
  #   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  # end

  def add_to_cart
    session[:cart] ||= []
    session[:cart] << params[:hair_id]
    redirect_to hairs_path, notice: "Added to cart!"
  end

end

app/controllers/hairs_controller.rb
class HairsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create ]
  before_action :set_hair, only: [:show, :edit, :update]

  def index
    @hairs = Hair.all
  end

  def show
    @order = Order.new
    @review = Review.new 
    @hair = Hair.find(params[:id])
    @reviews = @hair.reviews
  end

  def new
    @hair = Hair.new
  end

  def create
    if current_user.admin?
      @hair = Hair.new(hair_params)
      @hair.admin = current_user
        if @hair.save
          redirect_to hairs_path(@hair), notice: "Hair successfully created!"
        else
          render :new, status: :unprocessable_entity
        end
    else
      redirect_to hairs_path(@hair), notice: "You are not authorized to add hair."
    end
  end

  def edit
  end

  def update
    if current_user.admin?
      @hair.admin = current_user
        if @hair.update(hair_params)
          redirect_to hairs_path(@hair), notice: "Hair successfully updated!"
        else
          render :edit, status: :unprocessable_entity
        end
    else
      redirect_to hairs_path(@hair), notice: "You are not authorized to add hair."
    end
  end

  private

  def set_hair
    @hair = Hair.find(params[:id])
  end

  def hair_params
    params.require(:hair).permit(:name, :price, :length, :texture, :origin, :quantity, :photo)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create
    @hair = Hair.find(params[:hair_id])
    @order = Order.new(order_params)
    @order.price = @hair.price * @order.quantity
    @order.user = current_user

    if @order.quantity > @hair.quantity
      redirect_to hair_path(@hair), alert: "Not enough stock available."
      return
    end

    if @order.save
      @hair.update(quantity: @hair.quantity - @order.quantity)
      redirect_to dashboard_path, notice: "Order placed successfully!"
    else
      redirect_to hair_path(@hair), status: :unprocessable_entity, notice: "Failed to create order"
    end
  end


  def checkout
    @hair = Hair.find(params[:hair_id])
    @order = @hair.orders.find(params[:id])

    session = Stripe::Checkout::Session.create(
      payment_method_types: ["card"],
      line_items: [{
        price_data: {
          currency: "usd",
          product_data: {
            name: @order.hair.name
          },
          unit_amount: (@order.price / @order.quantity * 100).to_i # Price per unit
        },
        quantity: @order.quantity
      }],
      mode: "payment",
      success_url: "#{request.base_url}#{success_hair_order_path(@hair, @order)}",
      cancel_url: "#{request.base_url}#{cancel_hair_order_path(@hair, @order)}"
    )

    redirect_to session.url, allow_other_host: true
  end

  def success
    @order = Order.find(params[:id])
    @order.update(status: "paid")
    redirect_to dashboard_path, notice: "Payment successful!"
  end

  def cancel
    redirect_to dashboard_path, alert: "Payment was canceled. Please try again."
  end

  private

  def order_params
    params.require(:order).permit(:hair_id, :quantity)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @threeHairs = Hair.limit(3)
    @hairs = Hair.all
  end

  def dashboard
    @user_bookings = Order.where(user_id: current_user.id)
    @orders = current_user.order.includes(:hair)
    @order = @orders.last
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create ]
  before_action :set_reviews, only: [ :edit, :update ]
  def new
    @hair = Hair.find(params[:hair_id])
    @review = Review.new
    @review.user = current_user
  end

  def create
    @hair = Hair.find(params[:hair_id])
    @review = Review.new(review_params)
    @review.hair = @hair
    @review.user = current_user
    if @review.save
      redirect_to hair_path(@hair), alert: "Your review has been successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    if @review.update
      redirect_to hair_path(@hair), alert: "Your review has been successfully edited."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_reviews
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hairs/_form.html.erb
<div class="conainter mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="mb-3">
        <%= simple_form_for(hair) do |f| %>
          <%= f.input :name %>
          <%= f.input :price %>
          <%= f.input :length, collection: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40], prompt: "Select Length" %>
          <%= f.input :texture, collection: ["Straight", "Body Wave", "Deep Wave", "Loose Wave", "Water Wave", "Kinky Curly", "Yaki Straight", "Kinky Straight", "Vietnamese Straight", "Cambodian Wavy", "Burmese Curly"], prompt: "Select Texture" %>
          <%= f.input :origin, collection: ["Peruvian", "Brazilian", "Indian"], prompt: "Select Origin" %>
          <%= f.input :quantity %>
          <%= f.input :photo, as: :file %>
          <%= f.submit  class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
 </div>

app/views/hairs/edit.html.erb
<h1 class="row justify-content-center">Edit a hair</h1>
<%= render 'form', hair: @hair %>

app/views/hairs/home.html.erb
<h1>Available Hair Products</h1>
<% @hairs.each do |hair| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Hair Details</h5>
      <p class="card-text">Price: £<%= hair.price %></p>
      <p class="card-text">Length: <%= hair.length %> inches</p>
      <p class="card-text">Texture: <%= hair.texture %></p>
      <p class="card-text">Origin: <%= hair.origin %></p>
    </div>
  </div>
<% end %>

app/views/hairs/index.html.erb
<h1>Available Hair Products</h1>
<% @hairs.each do |hair| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Hair Details</h5>
      <p class="card-text">Price: £<%= hair.price %></p>
      <p class="card-text">Length: <%= hair.length %> inches</p>
      <p class="card-text">Texture: <%= hair.texture %></p>
      <p class="card-text">Origin: <%= hair.origin %></p>
      <%= link_to hair.name, hair_path(hair) %>
    </div>
  </div>
<% end %>

app/views/hairs/new.html.erb
<h1 class="row justify-content-center">Add a new hair</h1>
<%= render 'form', hair: @hair %>

app/views/hairs/show.html.erb
<div class="row">
  <h1><%= @hair.name %></h1>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Hair Details</h5>
        <p class="card-text">Price: £<%= @hair.price %></p>
        <p class="card-text">Length: <%= @hair.length %> inches</p>
        <p class="card-text">Texture: <%= @hair.texture %></p>
        <p class="card-text">Origin: <%= @hair.origin %></p>
      </div>
    </div>
</div>
<div>
  <h2>Order your hair</h2>
  <%= simple_form_for [@hair, @order] do |f| %>
    <%= f.hidden_field :hair_id, value: @hair.id %>
    <%= f.input :quantity, collection: (1..100).to_a, prompt: "How many?" %>
    <%= f.submit "Place your order", class: "btn btn-primary" %>
  <%  end %>
</div>
<div>
  <h2><strong>Reviews</strong></h2>
  <ul class="list-group">
    <% @hair.reviews.each do |review| %>
      <li class="list-group-item"><%= review.content %></li>
    <% end %>
  </ul>
  <%= link_to 'Leave a review', new_hair_review_path(@hair) %>
  <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HairSales</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Make your payment</h1>
<% if @order.present? && @order.hair.present? %>
  <%= link_to "Proceed to Checkout", checkout_hair_order_path(@order.hair, @order), class: "btn btn-primary" %>
<% else %>
  <p>No pending orders found.</p>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_form.html.erb
<div class="conainter mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="mb-3">
        <%= simple_form_for [@hair, @review] do |f| %>
          <%= f.input :content %>
          <%= f.submit "Submit review", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<h1 class="row justify-content-center">Edit your review</h1>
<%= render 'form', review: @review %>

app/views/reviews/new.html.erb
<h1 class="row justify-content-center">Add a new review</h1>
<%= render 'form', review: @review %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>